services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: ['../src/{Controller,Document,Kernel.php}']

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
